server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#  error:
#    whitelabel:
#      enabled: false

spring:
  servlet:
      multipart:
        enabled: true
        max-file-size: 100MB
        max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/gongguiljeong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
  #      connection-timeout: 3000
  #      validation-timeout: 3000
  #      minimum-idle: 5
  #      maximum-pool-size: 20
  #      idle-timeout: 200000
  #      max-lifetime: 240000
  #      pool-name: hikari_pool
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        use_sql_comments: true
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 2000
        one-indexed-parameters: on # paging 1부터 시작하기

logging.level:
  #  root: info
  #  org.springframework:
  #    web: info
  #    security: info
  #    boot: info
  org.hibernate.SQL: debug
  org.hibernate.type: trace

springdoc:
  packages-to-scan: com.gongguiljeong
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api
    groups:
      enabled: true
  cache:
    disabled: true
  swagger-ui:
    path: /ui
    operations-sorter: alpha, method
    tags-sorter: alpha, method
#로깅 파일
#logging:
#  file:
#    name: ./logs/log.log
#org.hibernate.type: trace



