server:
  port: 5000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/ebdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 50
    open-in-view: false

  sql:
    init:
      mode: never

  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 2000
        one-indexed-parameters: on



springdoc:
  packages-to-scan: com.ddungja.petmily
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api
    groups:
      enabled: true
  cache:
    disabled: true
  swagger-ui:
    path: /ui
    operations-sorter: alpha, method
    tags-sorter: alpha, method


