### 브랜드 생성
POST {{host}}/brands
Content-Type: application/json

{
  "name": "G마켓",
  "link": "https://www.gmarket.co.kr/"
}


### 어드민 생성

POST {{host}}/admins
Content-Type: application/json

{
  "loginId" : "rldh1111",
  "password" :"qwer",
  "name" : "권기오",
  "email" : "rldh9037@naver.com",
  "brandId" : 1
}

### 인플루언서 생성
POST {{host}}/influencers
Content-Type: application/json

{
  "name": "권기오",
  "link" : "https://www.instagram.com/giogweon/"
}


### 메인 카테고리 생성
POST {{host}}/mainCategories
Content-Type: application/json

{
  "name": "푸드"
}

<> 2023-05-29T141547.400.json
<> 2023-05-29T141505.400.json

### 서브 카테고리 생성
POST {{host}}/subCategories
Content-Type: application/json

{
  "name": "음료",
  "mainCategoryId" : 1
}

<> 2023-05-29T141642.400.json


###
GET {{host}}/brands/1
Content-Type: application/json

<> 2023-05-29T224536.401.json
<> 2023-05-29T224530.401.json
<> 2023-05-29T224525.401.json
<> 2023-05-29T224512.401.json
<> 2023-05-29T224511.401.json
<> 2023-05-29T224510.401.json
<> 2023-05-29T224507.401.json
###
PUT {{host}}/brands/{{id}}

###
GET {{host}}/user

<> 2023-05-29T122637.200.txt

###
GET {{host}}/gongguiljeongs

###
POST {{host}}/gongguiljeongs

###
GET {{host}}/gongguiljeongs/{{id}}

###
PUT {{host}}/gongguiljeongs/{{id}}

###
DELETE {{host}}/gongguiljeongs/{{id}}

###

